# Generated by Django 5.0.3 on 2024-03-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
