# Generated by Django 5.0.3 on 2024-03-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_delete_specialization'),
        ('patient', '0002_delete_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('number', models.TextField(max_length=100, null=True)),
                ('time', models.TimeField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('message', models.TextField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
