# Generated by Django 5.0.3 on 2024-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('passowrd', models.TextField(max_length=100, null=True)),
                ('specialization', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
